services:
  mysql:
    image: mysql:8.0
    container_name: nsfw_filter_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nsfw_filter_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: nsfw_filter_app
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: nsfw_filter_db
      SECRET_KEY: your-super-secret-docker-jwt-key
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 